theme = "myppuccin"

[editor]
rulers = [80]

# Color the mode indicator to match the cursor.
color-modes = true

# Remove extra gutters, save space
gutters = ["diagnostics"]

# Highlight any line containing a cursor.
cursorline = true

trim-final-newlines = true
trim-trailing-whitespace = true

# Show all diagnostics at the end of the line
end-of-line-diagnostics = "hint"

popup-border = "all"
auto-format = false

[editor.inline-diagnostics]
# Expand info+ diagnostics
cursor-line = "info"

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "â†’"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"

[editor.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'

[keys.normal]
# Enable tab as structure-aware forward nav
tab = "move_parent_node_end"
# Enable Shift-tab as structure-aware backward nav
S-tab = "move_parent_node_start"

[keys.insert]
# tab is already forward nav due to smart-tab
# Also enable backward nav
S-tab = "move_parent_node_start"
# Allow inserting a tab anywhere with ^Tab, overrides smarts
C-tab = "insert_tab"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
